### ISSUE TITLE
No longer able to login (using Client_Id & Client secret 400 error

### ISSUE THREAD

**Issue by NPSconsultingLLC** [tjmehta/homebridge-eightsleep-platform#23]
I am no longer able to login with this plugin, and I'm not sure how to debug any further. This is the error Im getting: 

`StatusCodeError: unexpected status
    at EightSleepClientApi.<anonymous> (/var/lib/homebridge/node_modules/homebridge-eightsleep-pod/node_modules/simple-api-client/src/index.ts:280:21)
    at Generator.next (<anonymous>)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge-eightsleep-pod/node_modules/simple-api-client/dist/cjs/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
{
  "expectedStatus": 200,
  "status": 400,
  "headers": {},
  "path": "login",
  "init": {
    "method": "POST",
    "headers": {
      "accept": "application/json",
      "content-type": "application/json",
      "user-agent": "Eight%20Sleep/1000018 CFNetwork/1237 Darwin/20.4.0",
      "accept-language": "en-us",
      "accept-encoding": "gzip, deflate, br"
    },
    "body": "{\"email\":\"Me@MyEmail.com\",\"password\":\"MySecurePassword\"}"
  },
  "body": {
    "status": 400,
    "code": "BadRequest",
    "error": "Error logging in."
  }
}`

This is what my config looks like: 

`        {
            "platform": "EightSleepPod",
            "email": "Me@MyEmail.com",
            "password": "MySecurePassword",
            "oauthClient": {
                "id": "08XXXXXXXX",
                "secret": "f095XXXXXXXXXXX"
            }
        }`

THanks for the time and I'm grateful for the plugin.

**Comment by davidjbradshaw** [comment]
That looks like the remote API changed. Are you still getting this issue?

**Comment by tjmehta** [comment]
any leads?

**Comment by tmm1** [comment]
seeing 401 error "session token not supported"

```
[10/8/2024, 8:49:33 AM] StatusCodeError: unexpected status
    at EightSleepClientApi.<anonymous> (/var/lib/homebridge/node_modules/homebridge-eightsleep-pod/node_modules/simple-api-client/src/index.ts:280:21)
    at Generator.next (<anonymous>)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge-eightsleep-pod/node_modules/simple-api-client/dist/cjs/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
{
  "expectedStatus": 200,
  "status": 401,
  "headers": {},
  "path": "users/me",
  "init": {
    "method": "GET",
    "headers": {
      "user-agent": "Eight%20Sleep/1000018 CFNetwork/1237 Darwin/20.4.0",
      "accept-language": "en-us",
      "accept-encoding": "gzip, deflate, br",
      "accept": "application/json",
      "user-id": "xxx",
      "session-token": "xxx-xxx"
    }
  },
  "body": {
    "status": 401,
    "code": "Unauthorized",
    "error": "session token not supported"
  }
}
