### ISSUE TITLE
UnhandledPromiseRejectionWarning: InvalidUserError: invalid currentDevice.side

### ISSUE THREAD

**Issue by aschi2** [tjmehta/homebridge-eightsleep-platform#3]
When running the plugin I get this error
`(node:28588) UnhandledPromiseRejectionWarning: InvalidUserError: invalid currentDevice.side
    at Object.validateUser [as default] (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/validateUser.ts:113:11)
    at EightSleepClientApi.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/index.ts:188:24)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/dist/cjs/index.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

I have omitted the oauth portion of the config as I am not sure where to get that information. The logs also print some of my account information so I am sure I have the correct login information in the config.

**Comment by tjmehta** [comment]
I haven't tested a eightsleep bed with a single side well (and I didn't want to reconfigure my bed to test it). If you can log what the device response looks like to you and then strip out and IDs and auth info, I think we can fix this. If you can add a log line above this line https://github.com/tjmehta/node-eightsleep/blob/master/src/validateUser.ts#L112 logging `currentDevice.side` inside your node_modules/eightsleep dir that would be a good start

**Comment by tjmehta** [comment]
bump @aschi2

**Comment by aschi2** [comment]
Sorry about that, I'll test this out this weekend.

**Comment by tjmehta** [comment]
fixed in v2.2.2, lmk if you still have problems. 
(correctly validates when currentDevice.side is "solo")

**Comment by aschi2** [comment]
Not sure if it's part of this same issue or a new issue but I'm still getting error messages. Though the accessory does show up in my homekit, it's not communicating.


[11/15/2020, 00:30:48] [EightSleepPod] Get CurrentTemperature
[11/15/2020, 00:30:48] [EightSleepPod] Get RotationSpeed
[11/15/2020, 00:30:48] [EightSleepPod] Get TargetHeaterCoolerState
[11/15/2020, 00:30:48] [EightSleepPod] Get Active
[11/15/2020, 00:30:48] [EightSleepPod] Get CurrentHeaterCoolerState
[11/15/2020, 00:30:48] [EightSleepPod] Get CurrentTemperature Error -> BaseError: appApiClient is missing (client should be instantiated with oauthClient)
    at EightSleepClientApi.getAppApiClient (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/index.ts:144:13)
    at EightSleepPod.getTemperature.memoize_concurrent_1.default.maxAge (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:147:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:31:22)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:4:12)
    at EightSleepPod.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:29:66)
    at EightSleepPod.getTemperature (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/mem/index.js:24:21)
    at CurrentTemperature.EightsleepPodPlatformAccessory.getCurrentTemperature (/usr/lib/node_modules/homebridge-eightsleep-pod/src/platformAccessory.ts:285:53)
    at CurrentTemperature.emit (events.js:315:20)
    at CurrentTemperature.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at CurrentTemperature.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1145:10)
[11/15/2020, 00:30:48] [EightSleepPod] Get TargetHeaterCoolerState Error -> BaseError: appApiClient is missing (client should be instantiated with oauthClient)
    at EightSleepClientApi.getAppApiClient (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/index.ts:144:13)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:44:20
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:31:22)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:4:12)
    at EightSleepPod.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:29:66)
    at EightSleepPod.getDeviceStatus (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/mem/index.js:24:21)
    at EightSleepPod.getStatus (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:48:37)
    at EightSleepPod.isOn (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:103:35)
    at Active.EightsleepPodPlatformAccessory.getActiveState (/usr/lib/node_modules/homebridge-eightsleep-pod/src/platformAccessory.ts:107:43)
    at Active.emit (events.js:315:20)
    at Active.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Active.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
[11/15/2020, 00:30:48] [EightSleepPod] Get CurrentHeaterCoolerState Error -> BaseError: appApiClient is missing (client should be instantiated with oauthClient)
    at EightSleepClientApi.getAppApiClient (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/index.ts:144:13)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:44:20
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:31:22)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:4:12)
    at EightSleepPod.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:29:66)
    at EightSleepPod.getDeviceStatus (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/mem/index.js:24:21)
    at EightSleepPod.getStatus (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:48:37)
    at EightSleepPod.isOn (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:103:35)
    at Active.EightsleepPodPlatformAccessory.getActiveState (/usr/lib/node_modules/homebridge-eightsleep-pod/src/platformAccessory.ts:107:43)
    at Active.emit (events.js:315:20)
    at Active.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Active.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
[11/15/2020, 00:30:48] [EightSleepPod] Get RotationSpeed Error -> BaseError: appApiClient is missing (client should be instantiated with oauthClient)
    at EightSleepClientApi.getAppApiClient (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/index.ts:144:13)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:44:20
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:31:22)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:4:12)
    at EightSleepPod.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:29:66)
    at EightSleepPod.getDeviceStatus (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/mem/index.js:24:21)
    at EightSleepPod.getStatus (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:48:37)
    at EightSleepPod.isOn (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:103:35)
    at Active.EightsleepPodPlatformAccessory.getActiveState (/usr/lib/node_modules/homebridge-eightsleep-pod/src/platformAccessory.ts:107:43)
    at Active.emit (events.js:315:20)
    at Active.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Active.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
[11/15/2020, 00:30:48] [EightSleepPod] Get Active Error -> BaseError: appApiClient is missing (client should be instantiated with oauthClient)
    at EightSleepClientApi.getAppApiClient (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/index.ts:144:13)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:44:20
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:31:22)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/dist/cjs/index.js:4:12)
    at EightSleepPod.<anonymous> (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/memoize-concurrent/src/index.ts:29:66)
    at EightSleepPod.getDeviceStatus (/usr/lib/node_modules/homebridge-eightsleep-pod/node_modules/mem/index.js:24:21)
    at EightSleepPod.getStatus (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:48:37)
    at EightSleepPod.isOn (/usr/lib/node_modules/homebridge-eightsleep-pod/src/EightSleepPod.ts:103:35)
    at Active.EightsleepPodPlatformAccessory.getActiveState (/usr/lib/node_modules/homebridge-eightsleep-pod/src/platformAccessory.ts:107:43)
    at Active.emit (events.js:315:20)
    at Active.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Active.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
