### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-eightsleep-pod:

### ISSUE THREAD

**Issue by NPSconsultingLLC** [tjmehta/homebridge-eightsleep-platform#7]
`====================
[19/12/2021, 21:23:26] ERROR LOADING PLUGIN homebridge-eightsleep-pod:
[19/12/2021, 21:23:26] ReferenceError: window is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/fast-abort-controller/src/index.ts:20:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/promise-backoff/src/index.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[19/12/2021, 21:23:26] ====================`

I have been trying to add the EightSleep Plugin but I keep getting this error after adding the plugin. My config looks like this: 

`{
    "platform": "EightSleepPod",
    "email": "n***********@gmail.com",
    "password": "************",
    "oauthClient": {
        "id": "0************************8",
        "secret": "f*********************************************6"
    }
}`

**Comment by tjmehta** [comment]
thanks will fix!

**Comment by tjmehta** [comment]
try v2.4.2 and lmk

**Comment by NPSconsultingLLC** [comment]
It now loads but there is a different error when I try and interact with the EightSleep Pod 

```
Get Active Error -> InvalidSideStatusError: invalid currentTargetLevel
    at validateSideStatus (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/validateDeviceStatus.ts:76:11)
    at Object.validateDeviceStatus [as default] (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/validateDeviceStatus.ts:52:12)
    at EightSleepAppApi.<anonymous> (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/EightSleepAppApi.ts:79:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/dist/cjs/EightSleepAppApi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
  "sideStatus": {
    "currentLevel": -79,
    "currentTargetLevel": 15,
    "currentActivity": "schedule",
    "version": 2,
    "smartTemperature": {
      "bedTimeLevel": 15,
      "initialSleepLevel": -10,
      "finalSleepLevel": 0,
      "currentPhase": "bedtime"
    }
  }
}
 {
  sideStatus: {
    currentLevel: -79,
    currentTargetLevel: 15,
    currentActivity: 'schedule',
    version: 2,
    smartTemperature: {
      bedTimeLevel: 15,
      initialSleepLevel: -10,
      finalSleepLevel: 0,
      currentPhase: 'bedtime'
    }
  }
}
```
And 

```
 Get RotationSpeed Error -> InvalidSideStatusError: invalid currentTargetLevel
    at validateSideStatus (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/validateDeviceStatus.ts:76:11)
    at Object.validateDeviceStatus [as default] (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/validateDeviceStatus.ts:52:12)
    at EightSleepAppApi.<anonymous> (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/src/EightSleepAppApi.ts:79:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/dist/cjs/EightSleepAppApi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
  "sideStatus": {
    "currentLevel": -79,
    "currentTargetLevel": 15,
    "currentActivity": "schedule",
    "version": 2,
    "smartTemperature": {
      "bedTimeLevel": 15,
      "initialSleepLevel": -10,
      "finalSleepLevel": 0,
      "currentPhase": "bedtime"
    }
  }
}
 {
  sideStatus: {
    currentLevel: -79,
    currentTargetLevel: 15,
    currentActivity: 'schedule',
    version: 2,
    smartTemperature: {
      bedTimeLevel: 15,
      initialSleepLevel: -10,
      finalSleepLevel: 0,
      currentPhase: 'bedtime'
    }
  }
}
```

**Comment by tjmehta** [comment]
got it I see.

1) I hadn’t tested a non left/right split bed and I was too lazy to reset mine to test it. thanks for sharing the error I see how to handle that now!

2) are you using the beta temperature settings feature or something**?** it’s interesting to see the target level a number not divisible by 10. I will make my response validation looser, to fix this.

thanks!

**Comment by tjmehta** [comment]
try v2.4.2 and lmk

**Comment by NPSconsultingLLC** [comment]
Yep its working now! Thanks for supporting this! I really appreciate it!

**Comment by tjmehta** [comment]
woohoo! enjoy :-)

**Comment by ftoralesacosta** [comment]
Hi! 

I wanted to post on this thread, because I'm one v 2.4.3 and am now getting the second set of errors posted above. I normally have the beta temperature setting _disabled_, but I get these errors now whether it's enabled or disabled. 

Pasting a subset of my errors below:
Get CurrentHeaterCoolerState Error -> InvalidSid
eStatusError: invalid currentTargetLevel
    at validateSideStatus (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightslee
p/src/validateDeviceStatus.ts:76:11)
    at Object.validateDeviceStatus [as default] (/usr/local/lib/node_modules/homebridge-eightsleep-pod/
node_modules/eightsleep/src/validateDeviceStatus.ts:51:11)
    at EightSleepAppApi.<anonymous> (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules
/eightsleep/src/EightSleepAppApi.ts:79:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/dist/cj
s/EightSleepAppApi.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
  "sideStatus": {
    "currentLevel": 7,
    "currentTargetLevel": 6,
    "currentActivity": "schedule",
    "version": 2,
    "smartTemperature": {
      "bedTimeLevel": 6,
      "initialSleepLevel": 10,
      "finalSleepLevel": 9,
      "currentPhase": "bedtime"
    }
  }
}
 {
  sideStatus: {
    currentLevel: 7,
    currentTargetLevel: 6,
    currentActivity: 'schedule',
    version: 2,
    smartTemperature: {
      bedTimeLevel: 6,
      initialSleepLevel: 10,
      finalSleepLevel: 9,
      currentPhase: 'bedtime'
    }
  }
}
[07/02/2022, 22:39:20] [EightSleepPod] Get TargetHeaterCoolerState Error -> InvalidSide
StatusError: invalid currentTargetLevel
    at validateSideStatus (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightslee
p/src/validateDeviceStatus.ts:76:11)
    at Object.validateDeviceStatus [as default] (/usr/local/lib/node_modules/homebridge-eightsleep-pod/
node_modules/eightsleep/src/validateDeviceStatus.ts:51:11)
    at EightSleepAppApi.<anonymous> (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules
/eightsleep/src/EightSleepAppApi.ts:79:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-eightsleep-pod/node_modules/eightsleep/dist/cj
s/EightSleepAppApi.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
  "sideStatus": {
    "currentLevel": 7,
    "currentTargetLevel": 6,
    "currentActivity": "schedule",
    "version": 2,
    "smartTemperature": {
      "bedTimeLevel": 6,
      "initialSleepLevel": 10,
      "finalSleepLevel": 9,
      "currentPhase": "bedtime"
    }
  }
}
 {
  sideStatus: {
    currentLevel: 7,
    currentTargetLevel: 6,
    currentActivity: 'schedule',
    version: 2,
    smartTemperature: {
      bedTimeLevel: 6,
      initialSleepLevel: 10,
      finalSleepLevel: 9,
      currentPhase: 'bedtime'
    }
  }
}
[07/02/2022, 22:39:20] [EightSleepPod] Get Active Error -> InvalidSideStatusError: inva


The logs look ok before this, but there is a warning that precedes this. Including this just in case it helps. Let me know if I can include more info!


This plugin slows down Homebridg
e. The read handler for the characteristic 'Active' didn't respond at all!. Please check that you properly 
call the callback! See https://git.io/JtMGR for more info.
[07/02/2022, 21:39:31] [homebridge-eightsleep-pod] This plugin slows down Homebridg
e. The read handler for the characteristic 'Current Heater-Cooler State' didn't respond at all!. Please che
ck that you properly call the callback! See https://git.io/JtMGR for more info.
[07/02/2022, 21:39:31] [homebridge-eightsleep-pod] This plugin slows down Homebridg
e. The read handler for the characteristic 'Target Heater-Cooler State' didn't respond at all!. Please chec
k that you properly call the callback! See https://git.io/JtMGR for more info.
[07/02/2022, 21:39:31] [homebridge-eightsleep-pod] This plugin slows down Homebridg
e. The read handler for the characteristic 'Rotation Speed' didn't respond at all!. Please check that you p
roperly call the callback! See https://git.io/JtMGR for more info.

**Comment by tjmehta** [comment]
Hey feel free to file a new bug. I'll try to take a look two weekends from now. The validation bug is an easy fix, just need to lax the rules in the eightsleep module. The homebridge warnings is something I've been meaning to get to.. might also be easy too. PRs welcome

**Comment by tjmehta** [comment]
homebridge-eightsleep-platform@v2.4.4
